services:
    kolyya_oauth.templating.helper:
        class: Kolyya\OAuthBundle\Templating\Helper\OAuthHelper
        public: false
        arguments: ['@security.token_storage','@templating','%kolyya_oauth%']
        tags:
            - { name: templating.helper, alias: kolyya_oauth }